name: Test and deploy
on:
  push:
    branches:
      - develop
      - feb-maint

jobs:
  deploy:
    name: Test and deploy to Kinsta staging environment
    runs-on: ubuntu-latest
    env:
      SFTP_HOST: ${{ secrets.KINSTA_SFTP_HOST }}
      SFTP_USER: ${{ secrets.KINSTA_SFTP_USER }}
      SFTP_PORT: ${{ secrets.KINSTA_STAGING_SFTP_PORT }}
    steps:
      - uses: actions/checkout@v4.2.2

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.KINSTA_SSH_KEY }}

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Add HTTP basic auth credentials
        env:
          COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH_JSON }}
        if: env.COMPOSER_AUTH != null
        run: echo '${{ secrets.COMPOSER_AUTH_JSON }}' > $GITHUB_WORKSPACE/auth.json

      - name: Install PHP dependencies
        uses: php-actions/composer@v6

      - name: Manually install rollup dependencies (see https://github.com/npm/cli/issues/4828#issuecomment-2404560937)
        run: npm i @rollup/rollup-linux-x64-gnu

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Test JavaScript
        run: npm run lint:scripts

      - name: Test PHP
        run: npm run lint:php

      - name: Reinstall only non-dev PHP dependencies
        uses: php-actions/composer@v6
        with:
          dev: no

      - name: Do the deploy
        run: ./bin/deploy
